### ISSUE TITLE
stopwords 임포트가 안 됩니다 ㅜ

### ISSUE THREAD

**Issue by jiyoonbaekbaek** [hexists/konlpy#1]
from konlpy.corpus import stopwords 라고 입력하였더니 ImportError: cannot import name 'stopwords' from 'konlpy.corpus' 라고 에러가 떴습니다. 처음엔 nltk 의 stopwords 와 겹쳐서 그런 줄 알고 nltk 를 삭제해봐도 해결되지 않습니다. 어떻게 하면 될까요 ?

**Comment by jiyoonbaekbaek** [comment]
해결하였습니다 !

**Comment by hexists** [comment]
@jiyoonbaekbaek 
해결됐다니 다행이네요. 잘 안되는 부분 있으면 이슈 남겨주세요~ 감사합니다.
