### ISSUE TITLE
안녕하세요 오류 때문에 연락드립니다.

### ISSUE THREAD

**Issue by Choiyoungmi0122** [hexists/konlpy#7]
설명을 보고 따라했는데 중간에 오류가 나서 연락드립니다.!

<img width="685" alt="image" src="https://user-images.githubusercontent.com/102124630/235886080-cc9baa8e-cb1d-42a9-98f8-6b950adf5691.png">

<img width="708" alt="image" src="https://user-images.githubusercontent.com/102124630/235885997-b25d59ee-d5d9-44b7-8234-50b28ec0b1f4.png">

현재 파이썬 버전은 
<img width="617" alt="image" src="https://user-images.githubusercontent.com/102124630/235886224-7ccb0203-06d1-44ae-b552-00a6a496491f.png">

m1 노트북을  사용하고 있습니다. 가상환경은 말씀하신것처럼은 저는 되지않아
python -m venv craw
source activate 를 이용하여
craw라는 가상환경에서 작업하고 있습니다.

감사합니다.

**Comment by hexists** [comment]
@Choiyoungmi0122 
안녕하세요.
위 에러는 pip와 관련된 에러로 보입니다.
pip가 잘 동작하는지 확인해보시면 좋을 것 같아요.

그리고, 현재 repo는 개인 작업을 위해 fork한 것으로 [원본 repo](https://github.com/konlpy/konlpy)에 이슈 남겨주세요.

현재 이슈는 konlpy와 관련된 것이 없어 종료하겠습니다.
